### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by ILikeTacos123** [kaboomserver/extras#313]
how do you add it to a eaglercraft server?

**Comment by ayunami2000** [comment]
**CHAOS AHAHHAHAHAHAHAHHAHHAHAHHA** i have brought chaos upon kaboom :trollface:

**Comment by ILikeTacos123** [comment]
TF

**Comment by ILikeTacos123** [comment]
can you just tell me how to add it lol

**Comment by allinkdev** [comment]
@ayunami2000 open src ur fork pls or link it

**Comment by ILikeTacos123** [comment]
I have a eaglercraft server so how do you put it on the server?

**Comment by ILikeTacos123** [comment]
(I run it on repl)

**Comment by allinkdev** [comment]
To install the plugin, you can either download the zip file of the GitHub repo, git clone it, or download a built from https://github.com/kaboomserver/server/blob/master/plugins/Extras.jar.

You can download the entirety of the "server" repo and that will give you a fully functioning Kaboom clone. 

Please note that Eaglercraft's modified Bungee/Bukkit is an untested version of Bungee, and we are not able to provide any sort of support for that. @ayunami2000 would be the person to go to on that.

Since REPLs have limited amounts of resources, performance will most likely not be the best. Your best option is to host it on your own computer, just for your friends.

I'm closing this issue as it isn't a bug report or a feature suggestion, which is what GitHub issues are for. If you want support, either ask @ayunami2000 or someone in the Eaglercraft/Spigot/Paper Discord, however I can't guarantee they'll support you.

Best of luck!
